rendering:
    resolution_view: 600
    milliseconds: 30

episode:
    episode_length: 400
    time_step: 0.25

robot:
    robot_radius: 0.25
    goal_radius: 0.35
    robot_type: "diff-drive"  # Options: diff-drive or holonomic.

human:
    human_diameter: 0.72
    human_goal_radius: 0.25
    human_policy: "orca"  # Options: random, sfm, or orca.
    gaze_angle: 3.14159
    fov_angle: 6.2831853
    prob_to_avoid_robot: 0.0

laptop:
    laptop_width: 0.4
    laptop_length: 0.6

plant:
    plant_radius: 0.6

table:
    table_width: 0.75
    table_length: 1.5

wall:
    wall_thickness: 0.2

human-human-interaction:
    interaction_radius: 0.72
    interaction_goal_radius: 1.44
    noise_variance: 0.005

human-laptop-interaction:
    human_laptop_distance: 0.3

env:
    margin: 0.5
    max_advance_human: 1.0
    max_advance_robot: 1.0
    max_rotation: 1.2
    wall_segment_size: 15
    speed_threshold: 0.005
    crowd_dispersal_probability: 0.0
    human_laptop_dispersal_probability: 0.0
    crowd_formation_probability: 0.0
    human_laptop_formation_probability: 0.0

    reward_file: "custom_rewards/socnavgym_social_safety_reward.py"  # Reward implementation path, sngnn, or dsrnn.

    cuda_device: 0
    
    min_static_humans: 2
    max_static_humans: 2

    min_dynamic_humans: 5
    max_dynamic_humans: 8

    min_tables: 0
    max_tables: 0

    min_plants: 3
    max_plants: 5

    min_laptops: 0
    max_laptops: 0

    min_h_h_dynamic_interactions: 0
    max_h_h_dynamic_interactions: 0

    min_h_h_dynamic_interactions_non_dispersing: 0
    max_h_h_dynamic_interactions_non_dispersing: 0

    min_h_h_static_interactions: 0
    max_h_h_static_interactions: 0

    min_h_h_static_interactions_non_dispersing: 0
    max_h_h_static_interactions_non_dispersing: 0

    min_human_in_h_h_interactions: 0
    max_human_in_h_h_interactions: 0

    min_h_l_interactions: 0
    max_h_l_interactions: 0

    min_h_l_interactions_non_dispersing: 0
    max_h_l_interactions_non_dispersing: 0

    get_padded_observations: True
    
    set_shape: "square"  # Options: random, square, rectangle, L, or no-walls.
    add_corridors: false

    min_map_x: 10
    max_map_x: 10

    min_map_y: 10
    max_map_y: 10
